[project]
name = "avito-orientation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.8",
    "datasets>=5.0.1",
    "huggingface-hub>=1.33.0",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "opencv-python-headless>=5.0.0.93",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.1",
]

[project.scripts]
avito-orientation = "avito_orientation:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
